import type { OptimizeOptions, OptimizeResult } from './types';

/**
 * Shape of the native addon generated by `napi build` (see package.json's
 * "build:native" script). That build step produces `index.js`/`index.d.ts`
 * at the project root, loading the platform-specific `.node` binary.
 *
 * This interface is declared by hand so the rest of the TypeScript layer
 * type-checks without requiring a Rust build first — run `npm run build`
 * before actually calling `optimizeImage` at runtime.
 */
interface NativeBinding {
  optimizeImage(inputPath: string, options?: OptimizeOptions): OptimizeResult;
}

let cached: NativeBinding | undefined;

function loadNative(): NativeBinding {
  if (!cached) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      cached = require('../index.js') as NativeBinding;
    } catch (error) {
      throw new Error(
        "ImageForge's native addon isn't built yet. Run `npm run build:native` " +
          `(or \`npm run build\`) first.\nOriginal error: ${(error as Error).message}`
      );
    }
  }
  return cached;
}

export function optimizeImage(inputPath: string, options?: OptimizeOptions): OptimizeResult {
  return loadNative().optimizeImage(inputPath, options);
}
